### ISSUE TITLE
Permissiosn in docker-compose.yml

### ISSUE THREAD

**Issue by devcode2** [IzakMarais/reporter#51]
Am I interpreting the permissions in docker-compose.yml correctly?
Do these settings allow an anonymous user to be an admin?  

```
GF_USERS_ALLOW_SIGN_UP: "false"
GF_AUTH_DISABLE_LOGIN_FORM: "true"
GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
GF_AUTH_ANONYMOUS_ENABLED: "true"
GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
```

Do you have instructions on how to install the report master behind a reverse proxy, with a custom port and with SSL?

I changed the port number 3000 to my port in these files:
cmd/grafana-reporter/main.go
util/docker-compose.yml

I also made these changes but I do not know if they are correct and what to do next.

```
  grafana:
    image: grafana/grafana:latest
    environment:
#      GF_USERS_ALLOW_SIGN_UP: "false"
#      GF_AUTH_DISABLE_LOGIN_FORM: "false"
#      GF_AUTH_DISABLE_SIGNOUT_MENU: "false"
#      GF_AUTH_ANONYMOUS_ENABLED: "false"
#      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
    expose:
      - 1234
    ports:
      - "1234:1234"

  reporter:
    image: izakmarais/grafana-reporter:${gr_version:-latest}
    command: "-ip grafana:1234"
    ports:
      - "443:8686"
```

Thanks
